INSERT INTO favourites (user_id, recipe_name) 
VALUES (1, 'Chicken Vesuvio'),
(2, 'Chicken Vesuvio'),
(3, 'Chicken Vesuvio'),
(5, 'Chicken Vesuvio'),
(2, 'Corn Cakes'),
(3, 'Corn Cakes'),
(4, 'Corn Cakes'),
(5, 'Corn Cakes'),
(6, 'Corn Cakes'),
(7, 'Corn Cakes'),
(2, 'Red Beans and Brown Rice'),
(3, 'Red Beans and Brown Rice'),
(4, 'Red Beans and Brown Rice'),
(5, 'Red Beans and Brown Rice'),
(6, 'Red Beans and Brown Rice'),
(1, 'French Red Onion Soup'),
(2, 'French Red Onion Soup'),
(5, 'French Red Onion Soup'),
(7, 'French Red Onion Soup'),
(1, 'Creamed Green Peas'),
(1, 'Spaghetti Carbonara'),
(2, 'Spaghetti Carbonara'),
(3, 'Spaghetti Carbonara'),
(5, 'Spaghetti Carbonara'),
(6, 'Spaghetti Carbonara'),
(7, 'Spaghetti Carbonara'),
(1, 'Garlic Cucumber Salad'),
(2, 'Garlic Cucumber Salad'),
(3, 'Garlic Cucumber Salad'),
(2, 'Roast Sirloin Of Beef'),
(5, 'Roast Sirloin Of Beef'),
(7, 'Roast Sirloin Of Beef'),
(1, 'Green Onion Pancakes'),
(2, 'Green Onion Pancakes'),
(3, 'Green Onion Pancakes'),
(5, 'Green Onion Pancakes'),
(7, 'Green Onion Pancakes'),
(1, 'Skinny carrot fries'),
(5, 'Skinny carrot fries'),
(7, 'Skinny carrot fries'),
(2, 'Mediterranean potato salad'),
(3, 'Mediterranean potato salad'),
(4, 'Mediterranean potato salad'),
(5, 'Sweet potato wedges'),
(7, 'Sweet potato wedges'),
(1, 'Bacon-Wrapped Scallions'),
(2, 'Bacon-Wrapped Scallions'),
(3, 'Bacon-Wrapped Scallions'),
(4, 'Bacon-Wrapped Scallions'),
(5, 'Bacon-Wrapped Scallions'),
(6, 'Bacon-Wrapped Scallions'),
(7, 'Bacon-Wrapped Scallions'),
(2, 'Italian Celery and Mushroom Salad'),
(3, 'Italian Celery and Mushroom Salad'),
(4, 'Italian Celery and Mushroom Salad'),
(5, 'Italian Celery and Mushroom Salad'),
(7, 'Italian Celery and Mushroom Salad'),
(5, 'Beef Brisket'),
(7, 'Beef Brisket'),
(5, 'Spicy Eggplant'),
(7, 'Spicy Eggplant'),
(5, 'Chicken cacciatore'),
(1, 'Creamy Mushroom Pasta Bake'),
(3, 'Creamy Mushroom Pasta Bake'),
(4, 'Creamy Mushroom Pasta Bake'),
(5, 'Creamy Mushroom Pasta Bake'),
(6, 'Creamy Mushroom Pasta Bake'),
(7, 'Creamy Mushroom Pasta Bake'),
(5, 'Portobello Mushroom Fries'),
(7, 'Portobello Mushroom Fries'),
(2, 'Portobello Mushroom Fries'),
(2, 'Mushroom Frittata'),
(7, 'Mushroom Frittata'),
(1, 'Chicken Paprikash'),
(2, 'Chicken Paprikash'),
(3, 'Chicken Paprikash'),
(5, 'Chicken Paprikash'),
(6, 'Chicken Paprikash'),
(7, 'Chicken Paprikash'),
(1, 'Seared Ahi Tuna'),
(2, 'Seared Ahi Tuna'),
(4, 'Seared Ahi Tuna'),
(5, 'Seared Ahi Tuna')