INSERT INTO favourites (userId, recipe_name) 
VALUES (7, 'Chicken Vesuvio'),
(7, 'Corn Cakes'),
(7, 'Red Beans and Brown Rice'),
(7, 'French Red Onion Soup'),
(7, 'Creamed Green Peas'),
(7, 'Spaghetti Carbonara'),
(7, 'Garlic Cucumber Salad'),
(7, 'Roast Sirloin Of Beef'),
(7, 'Green Onion Pancakes'),
(7, 'Skinny carrot fries'),
(7, 'Mediterranean potato salad'),
(7, 'Sweet potato wedges'),
(7, 'Raw Pickled Beets recipes'),
(7, 'Bacon-Wrapped Scallions'),
(7, 'Italian Celery and Mushroom Salad'),
(7, 'Beef Brisket'),
(7, 'Spicy Eggplant'),
(7, 'Chicken cacciatore'),
(7, 'Creamy Mushroom Pasta Bake'),
(7, 'Portobello Mushroom Fries'),
(7, 'Mushroom Frittata')