DROP TABLE IF EXISTS dates CASCADE;
CREATE TABLE dates (
id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
date DATE NOT NULL,
recipe_id INTEGER REFERENCES recipes(id) ON DELETE CASCADE NOT NULL,
meal_number INTEGER
);