DROP TABLE IF EXISTS slots CASCADE;
CREATE TABLE slots (
  id SERIAL PRIMARY KEY NOT NULL,
  date_id INTEGER REFERENCES date(id) ON DELETE CASCADE NOT NULL,
  favourite_id INTEGER REFERENCES favourites(id) ON DELETE CASCADE
);