DROP TABLE IF EXISTS calendar CASCADE;
CREATE TABLE calendar (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  recipe_name VARCHAR(255) NOT NULL,
);